Fix a narrowing conversion error spotted by gcc
Full error:
error: narrowing conversion of ‘2147577989ul’ from
‘long unsigned int’ to ‘int’ inside { } [-Wnarrowing]

The second parameter of ioctl where the arrays are used is an unsigned long.